### ISSUE TITLE
Don't expand #'... for macros

### ISSUE THREAD

**Issue by Wilfred** [Malabarba/speed-of-thought-lisp#11]
I tend to define functions with names `wh/something`. This causes problems with `sotlisp--default-function-abbrevs` containing `"wh"`, because typing `#'wh/` expands to `#'while/`.

I know this is probably going to impact me more than other users due to my initials :). However, it's not useful to expand `#'wh` to `#'while`, so would it be possible to refuse to expand `#'foo` to anything that isn't bound as a function?

**Comment by Malabarba** [comment]
Makes sense. Honestly though, maybe sotlisp expansions shouldn't be triggered at all by keys like `-` or `/`. I think that's more of an oversight than a feature.

**Comment by Malabarba** [comment]
I've changed the predicate to only expand when the keypress is not a symbol-syntax character. Let me know if it solved your problem.

**Comment by Wilfred** [comment]
Works, thank you :)
