### ISSUE TITLE
Infinite loop in 'sotlisp-uncomment-sexp'

### ISSUE THREAD

**Issue by nonsequitur** [Malabarba/speed-of-thought-lisp#3]
When applied on a comment without sexps, `sotlisp-uncomment-sexp` enters an infinite loop at line 612 (`(while (= end (save-excursion ...`, as of commit 838016).

Minimal example:

```
(pop-to-buffer "*infinite-loop*")
(emacs-lisp-mode)
(insert ";")
(sotlisp-uncomment-sexp)
```

**Comment by Malabarba** [comment]
Thanks for the report, I'll fix it as soon as I get a chance.
