### ISSUE TITLE
Expansion requires abbrev-mode to be active

### ISSUE THREAD

**Issue by Wilfred** [Malabarba/speed-of-thought-lisp#5]
I'm not sure if this should just be documented, or whether speed-of-thought-mode should automatically enable abbrev-mode. Still, enabling speed-of-thought-mode doesn't give the expansions without it, unless I'm doing something wrong.

**Comment by Malabarba** [comment]
No, you're correct. I think I'll just auto-enable abbrev-mode in these buffers. People who don't use abbrev-mode probably won't be bothered by this.
