### ISSUE TITLE
Possible unexpected behavior in sotlisp-comment-or-uncomment-sexp

### ISSUE THREAD

**Issue by djr7C4** [Malabarba/speed-of-thought-lisp#6]
Thanks for creating this mode.

Perhaps this is the intended behavior, but I find it strange.  By default `sotlisp-comment-or-uncomment-sexp` comments/uncomments the sexp before the cursor if the cursor is immediately after an sexp.  For example, in the following buffer where "|" denotes the cursor

```
(list 'a 'b| 'c)
```

running `sotlisp-comment-or-uncomment-sexp` results in

```
(list 'a ;; 'b
      'c)
```

while running it in the case of 

```
(list 'a 'b |'c)
```

results in

```
(list 'a 'b ;; 'c
      )
```

**Comment by Malabarba** [comment]
Yes, it's the intended behaviour. It tries to act on the sexp at point, so it works even if the point is immediately after the sexp.

**Comment by djr7C4** [comment]
Fair enough.  Thanks.
